#!/bin/sh
#==============================================================================
#       _                 _
#      | |               | |
#    __| |_ __ ___    ___| |__
#   / _` | '_ ` _ \  / __| '_ \
#  | (_| | | | | | |_\__ \ | | |
#   \__,_|_| |_| |_(_)___/_| |_|
#
#==============================================================================

#==============================================================================
# SANE ENVIRONMENT
#==============================================================================

set -e  # Exit on error.
set -u  # Unbound variable safe guard.

#==============================================================================
# INITIAL PATH CHANGE
#==============================================================================

DM__GLOBAL__RUNTIME__PATH="$(dirname "$(readlink -f "$0")")"
cd "${DM__GLOBAL__RUNTIME__PATH}"

#==============================================================================
# COMMAND LINE ARGUMENTS
#==============================================================================

# Temporary parameters file path that is generated by the Makefile target
# before calling this script by writing the user editable parameters to the
# temporary parameter file in a specific order. It is important to keep this
# order in sync between the Makefile and this script. This script has to delete
# the temporary file after getting all parameters from it.
DM__PARAMETER_FILE_PATH="$1"

# Flag that is passed from the Makefile to signal that global debugging is
# enabled. If the value is not `0`, then the debug messages will be printed to
# the standard error output of the dm process.
DM__GLOBAL__RUNTIME__DEBUG_ENABLED="$2"


echo "$DM__PARAMETER_FILE_PATH"
echo "$DM__GLOBAL__RUNTIME__DEBUG_ENABLED"
cat "$DM__PARAMETER_FILE_PATH"
